# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FcXQSK28Se0ih3sW8tfpSht2blAyW41r
"""

# --- 6. MAIN EXECUTION BLOCK ---
if __name__ == '__main__':

    # --- CHOOSE WHICH ANALYSIS TO RUN ---
    RUN_SINGLE_EXPLANATION = False
    RUN_FIGURE_5 = True  # ✅ We want to generate the multi-example figure.
    RUN_FIGURE_6 = False
    RUN_TABLE_1 = False
    RUN_TABLE_2 = False
    # ------------------------------------

    # 🚨 STEP 1: UPLOAD YOUR IMAGES using the file browser.
    # 🚨 STEP 2: Use the Diagnostic Tool to make sure they work.

    # 🚨 STEP 3: CONFIGURE YOUR EXAMPLES HERE
    # Edit the 'path' to be the exact filename of your uploaded image.
    # Edit the 'objects' to be the classes you want to analyze.
    example_set = [

        {
            'path': '/content/download (4).jpg', # <--- CHANGE TO YOUR FILENAME
            'objects': ('car', 'traffic light')
        }
    ]
    # --------------------------------------------------------------------

    # --- MODEL INITIALIZATION ---
    # This initializes the main processor.
    print("Initializing model processor...")
    processor = YOLOv5_Processor(model_name='yolov5x6', device=DEVICE)

    # --- RUN BATCH ANALYSIS FOR FIGURE 5 ---
    # This section now uses your manually configured 'example_set'
    if RUN_FIGURE_5:
        # The 'generate_figure_5_examples' function uses the robust
        # two-pass detection logic we developed.
        generate_figure_5_examples(processor, example_set)

    # The other analysis flags are False, so their blocks will be skipped.
    if any([RUN_SINGLE_EXPLANATION, RUN_FIGURE_6, RUN_TABLE_1, RUN_TABLE_2]):
        print("\nSkipping other analyses.")